config/routes.rb
Rails.application.routes.draw do
  root 'position#index'
  get 'position/scraper'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/position.rb
class Position < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/position_controller.rb
class PositionController < ApplicationController
  def index
    @positions = positions
  end

  def scraper
    Scraper.scrape
    # if !positions.empty?
    #   PositionMailer.update(positions).deliver_now
    # end
    redirect_to root_path
  end

  private

  def positions
    Position.where('created_at > ?', 24.hours.ago).order('created_at ASC').reverse_order
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobScrapperApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/position/index.html.erb
<button> <%= link_to "Scrapping for new positions", position_scraper_path %> </button>

<table style="width:50%">
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>Link</th>
    <th>Website</th>
  </tr>
  <% if @positions %>
    <% @positions.each do |position| %>
      <tr>
        <td>
          <%= position.title %>
        </td>
        <td>
          <%= position.company %>
        </td>
        <td>
          <a href="<%= position.link %>"> Link <a>
        </td>
        <td>
          <%= position.website %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>